notifications:
  email:
    recipients:
      - rahulavd@uw.edu
    on_success: change
    on_failure: always

language: python

python:
  - "3.5"

branches:
  only:
    - master

sudo: false

install:
  - pip install -r requirements.txt
  - pip install xlrd
  - pip install coveralls
  - pip install nose-exclude
  - python setup.py install

script:
  - nosetests --with-doctest --with-coverage --cover-package=ceo --exclude-dir=test/external --exclude-dir=extern --where=ceo

after_success:
    - coveralls
